### ISSUE TITLE
frontend - href problem with sidebar

### ISSUE THREAD

**Issue by Khip01** [AlexanderDev2004/RegIT#20]
## Mahasiswa Role
Can't redirect to Beranda Section, Pelanggaran Section and Profil Saya Section when on route:

```
Route: 
- RegIT/mahasiswa/profil/edit
``` 

## Dosen Role
Can't redirect to Beranda Section, Form Section, Pelanggaran Section and Profil Saya Section when on route:

```
Route: 
- RegIT/dosen/pelanggaran/1
- RegIT/dosen/profil/edit
``` 

## Komdis Role
Can't redirect to Beranda Section, Form Section, Pelanggaran Section and Profil Saya Section, etc when on route:

```
Route: 
- RegIT/komdis/pelanggaran/1
- RegIT/komdis/pelanggaran/1/edit
- RegIT/komdis/profil/edit
```

**Comment by om-ica** [comment]
check it
